export const WORKFLOW_STATUS = Object.freeze({
  PENDING_LAUNCH: 'PENDING_LAUNCH',
  LAUNCHED: 'LAUNCHED',
  PENDING_REPORT: 'PENDING_REPORT',
  REPORT_SUBMITTED: 'REPORT_SUBMITTED',
  LEARNINGS_SUBMITTED: 'LEARNINGS_SUBMITTED',
  BRIEF_SUBMITTED: 'BRIEF_SUBMITTED',
  BRIEF_APPROVED: 'BRIEF_APPROVED',
  PRODUCTION: 'PRODUCTION',
  INTERNAL_REVIEW: 'INTERNAL_REVIEW',
  CLIENT_REVIEW: 'CLIENT_REVIEW',
  CLIENT_APPROVED: 'CLIENT_APPROVED',
  READY_TO_LAUNCH: 'READY_TO_LAUNCH',
  REVISION_REQUESTED: 'REVISION_REQUESTED',
  HANDOFF: 'HANDOFF',
  COMPLETED: 'COMPLETED',
  PAUSED: 'PAUSED'
});

export const REVIEW_STATUS = Object.freeze({
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REVISE: 'REVISE',
  REJECTED: 'REJECTED'
});

export const ABHISHEK_DECISION = Object.freeze({
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  REVISION_REQUESTED: 'REVISION_REQUESTED'
});

export const TIMELINE_ACTION = Object.freeze({
  RECORD_CREATED: 'RECORD_CREATED',
  ASSIGNMENT_CHANGED: 'ASSIGNMENT_CHANGED',
  ASSIGNMENT_CREATED: 'ASSIGNMENT_CREATED',
  ASSIGNMENT_UPDATED: 'ASSIGNMENT_UPDATED',
  ASSIGNMENT_REASSIGNED: 'ASSIGNMENT_REASSIGNED',
  SCHEDULE_CREATED: 'SCHEDULE_CREATED',
  SCHEDULE_UPDATED: 'SCHEDULE_UPDATED',
  STAGE_CHANGED: 'STAGE_CHANGED',
  CREATIVE_LAUNCHED: 'CREATIVE_LAUNCHED',
  REPORT_SUBMITTED: 'REPORT_SUBMITTED',
  PERFORMANCE_ANALYSIS_SUBMITTED: 'PERFORMANCE_ANALYSIS_SUBMITTED',
  CREATIVE_ANALYSIS_SUBMITTED: 'CREATIVE_ANALYSIS_SUBMITTED',
  LEARNINGS_SUBMITTED: 'LEARNINGS_SUBMITTED',
  DESIGNER_ASSIGNED: 'DESIGNER_ASSIGNED',
  BRIEF_CREATED: 'BRIEF_CREATED',
  BRIEF_APPROVED: 'BRIEF_APPROVED',
  BRIEF_REVIEWED: 'BRIEF_REVIEWED',
  PRODUCTION_STARTED: 'PRODUCTION_STARTED',
  CREATIVE_SUBMITTED: 'CREATIVE_SUBMITTED',
  INTERNAL_REVIEW_APPROVED: 'INTERNAL_REVIEW_APPROVED',
  INTERNAL_REVIEW_DECISION: 'INTERNAL_REVIEW_DECISION',
  CLIENT_REVIEW_STARTED: 'CLIENT_REVIEW_STARTED',
  CLIENT_APPROVED: 'CLIENT_APPROVED',
  FINAL_APPROVAL_DECISION: 'FINAL_APPROVAL_DECISION',
  REVISION_REQUESTED: 'REVISION_REQUESTED',
  READY_TO_LAUNCH: 'READY_TO_LAUNCH',
  HANDED_OFF: 'HANDED_OFF',
  CYCLE_COMPLETED: 'CYCLE_COMPLETED',
  NEXT_CYCLE_CREATED: 'NEXT_CYCLE_CREATED',
  CYCLE_PAUSED: 'CYCLE_PAUSED',
  CYCLE_RESUMED: 'CYCLE_RESUMED',
  RECORD_UPDATED: 'RECORD_UPDATED'
});
